#Exercício Python 004: Faça um programa que leia algo pelo teclado e mostre na tela o seu tipo primitivo e todas as informações possíveis sobre ele.
n = input('Digite: ')
print('O tipo primitivo do valor?',type(n))
print('é um numero?',n.isnumeric())
print('é alfabético?',n.isalpha())
print('é alfanumérico?',n.isalnum())
print('tem espaco?',n.isspace())
print('é maiúscula?',n.isupper())
print('é minúscula?',n.islower())
print('é capitalizada?',n.istitle())
